import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  Switch,
  ActivityIndicator,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import DateTimePicker from "@react-native-community/datetimepicker";
import AppHeader from "../../reuseComponet/header";
import { addBillLocal } from "../../../database/SQLite";
import { Picker } from '@react-native-picker/picker';
import { useUser } from "../../reuseComponet/UserContext"; // 导入 useUser

export default function AddBill({ navigation }) {
  const [billName, setBillName] = useState("");
  const [category, setCategory] = useState("");
  const [amount, setAmount] = useState("");
  const [dueDate, setDueDate] = useState(new Date());
  const [showPicker, setShowPicker] = useState(false);
  const [isCommitment, setIsCommitment] = useState(false);
  const periodType = ["Yearly", "Monthly"];
  const [isLoading, setIsLoading] = useState(false);

  const [isPeriodic, setIsPeriodic] = useState(false);
  const [selectedType, setSelectedType] = useState("Yearly");
  const [periodInterval, setPeriodInterval] = useState(0);

  const { userId, isLoading: userLoading } = useUser(); 

  const categories = [
    "Rent / Mortgage",
    "Utilities",
    "Internet / Phone",
    "Insurance",
    "Credit Card Payment",
    "Loan Repayment",
    "Subscription",
    "Groceries / Food",
    "Transportation / Fuel",
    "Education / Tuition",
    "Medical / Health Expenses",
    "Household / Maintenance",
    "Entertainment / Leisure",
    "Others",
  ];
    const validateAmount = (value, fieldName = "Amount") => {
    if (!value || value === "") {
      triggerShake();
      Alert.alert(`Missing ${fieldName}`, `Please enter ${fieldName.toLowerCase()}.`);
      return false;
    }
  
    if (isNaN(value)) {
      triggerShake();
      Alert.alert(`Invalid ${fieldName}`, `${fieldName} must be numeric.`);
      return false;
    }
  
    const num = parseFloat(value);
    if (num <= 0) {
      triggerShake();
      Alert.alert(`Invalid ${fieldName}`, `${fieldName} must be greater than 0.`);
      return false;
    }
  
    if (num > 9999999999999999) {
      triggerShake();
      Alert.alert(
        `Invalid ${fieldName}`,
        `${fieldName} cannot exceed 9,999,999,999,999,999.`
      );
      return false;
    }
  
    return true;
  };

const handleSave = async () => {
  console.log("🔥 Saving Bill...");

  // 1️⃣ BILL NAME VALIDATION
  if (!billName || !billName.trim()) {
    return Alert.alert("Missing Bill Name", "Please enter a bill name.");
  }

  // 2️⃣ AMOUNT VALIDATION (Reuse your validateAmount!)
  if (!validateAmount(amount, "Bill Amount")) return;

  const amountValue = parseFloat(amount);

  // 3️⃣ DUE DATE VALIDATION
  if (!dueDate) {
    return Alert.alert("Missing Due Date", "Please select a due date.");
  }

  // 4️⃣ USER ID VALIDATION
  if (!userId) {
    return Alert.alert("Error", "User not logged in");
  }

  try {
    setIsLoading(true);

    await addBillLocal({
      userId,
      billName: billName.trim(),
      category,
      amount: amountValue,
      dueDate: dueDate.toISOString().split("T")[0],
      isAutoGenerated: isPeriodic ? 1 : 0,
      isCommitment: isCommitment ? 1 : 0,
      periodType: isPeriodic ? selectedType : "Yearly",
      periodInterval: isPeriodic ? Number(periodInterval) : 0,
    });

    Alert.alert("Success", "Bill added successfully!");
    navigation.goBack();

  } catch (error) {
    console.error("❌ addBillLocal error:", error);
    Alert.alert("Error", "Failed to add bill.");
  } finally {
    setIsLoading(false);
  }
};


  if (userLoading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#8AD0AB" />
        <Text>Loading user data...</Text>
      </View>
    );
  }


  if (!userId) {
    return (
      <View style={{ flex: 1 }}>
        <AppHeader
          title="Add New Bill"
          showLeftButton={true}
          onLeftPress={() => navigation.goBack()}
        />
        <View style={styles.errorContainer}>
          <Ionicons name="person-circle-outline" size={64} color="#6B7280" />
          <Text style={styles.errorTitle}>Please Log In</Text>
          <Text style={styles.errorMessage}>You need to be logged in to add bills</Text>
        </View>
      </View>
    );
  }

  return (
    <View style={{ flex: 1 }}>
      <AppHeader
        title="Add New Bill"
        showLeftButton={true}
        onLeftPress={() => navigation.goBack()}
      />

      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.label}>Bill Name</Text>
        <TextInput
          style={styles.input}
          placeholder="e.g. Credit Card"
          value={billName}
          onChangeText={setBillName}
          maxLength={50}
        />

        <View style={{ marginBottom: 12 }}>
          <Text style={styles.label}>Category</Text>
          <View style={styles.pickerContainer}>
            <Picker
              selectedValue={category}
              onValueChange={(itemValue) => setCategory(itemValue)}
            >
              <Picker.Item label="Select category..." value="" />
              {categories.map((c) => (
                <Picker.Item key={c} label={c} value={c} />
              ))}
            </Picker>
          </View>
        </View>

        <Text style={styles.label}>Amount (RM)</Text>
        <TextInput
          style={styles.input}
          placeholder="Enter amount"
          keyboardType="numeric"
          value={amount}
          onChangeText={setAmount}
        />

        <Text style={styles.label}>Due Date</Text>
        <TouchableOpacity style={styles.dateInput} onPress={() => setShowPicker(true)}>
          <Ionicons name="calendar-outline" size={18} color="#6c757d" />
          <Text style={styles.dateText}>
            {dueDate.toLocaleDateString('en-GB', {
              day: 'numeric',
              month: 'short',
              year: 'numeric'
            })}
          </Text>
        </TouchableOpacity>

        {showPicker && (
          <DateTimePicker
            value={dueDate}
            mode="date"
            display="default"
            onChange={(event, date) => {
              setShowPicker(false);
              if (date) setDueDate(date);
            }}
          />
        )}

        {/* Periodic Switch */}
        <View style={styles.periodicContainer}>
          <Text style={styles.label}>Is it periodic?</Text>
          <Switch
            value={isPeriodic}
            onValueChange={setIsPeriodic}
            trackColor={{ false: "#ccc", true: "#9cd8b3" }}
            thumbColor={isPeriodic ? "#4CAF50" : "#f4f3f4"}
          />
        </View>

        {/* Period Type Selection Bar */}
        {isPeriodic && (
          <>
            <View style={styles.periodicPicker}>
              <View style={styles.selectionBarContainer}>
                {periodType.map((type, index) => (
                  <TouchableOpacity
                    key={index}
                    style={[
                      styles.typeButton,
                      selectedType === type && styles.typeButtonActive,
                    ]}
                    onPress={() => setSelectedType(type)}
                  >
                    <Text
                      style={[
                        styles.typeButtonText,
                        selectedType === type && styles.typeButtonTextActive,
                      ]}
                    >
                      {type}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
            </View>

            <Text style={styles.label}>Repeat every:</Text>
            <View style={styles.pickerContainer}>
              <Picker
                selectedValue={periodInterval}
                onValueChange={(val) => setPeriodInterval(val)}
              >
                {[1, 2, 3, 6, 12].map((n) => (
                  <Picker.Item key={n} label={`${n}`} value={n} />
                ))}
              </Picker>
            </View>
          </>
        )}


        <View style={styles.toggleRow}>
          <View style={{ flexDirection: "row", alignItems: "center" }}>
            <Text style={styles.label}>Count as Loan Commitment?</Text>
            <TouchableOpacity
              style={{ marginLeft: 6 }}
              onPress={() =>
                Alert.alert(
                  "What is Loan Commitment?",
                  "Select 'Yes' if this bill is a loan or financing repayment that counts towards your debt service ratio (DSR).\n\nExamples:\n- Credit card minimum payment\n- Personal loan\n- Car loan\n- Mortgage\n- Hire purchase"
                )
              }
            >
              <Ionicons name="information-circle-outline" size={18} color="#6c757d" />
            </TouchableOpacity>
          </View>

          <TouchableOpacity
            style={[
              styles.toggleBtn,
              isCommitment ? styles.toggleOn : styles.toggleOff,
            ]}
            onPress={() => setIsCommitment(!isCommitment)}
          >
            <Text style={styles.toggleText}>{isCommitment ? "Yes" : "No"}</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity 
          style={[
            styles.saveBtn, 
            (isLoading || !billName.trim() || !amount || !category) && styles.saveBtnDisabled
          ]} 
          onPress={handleSave}
          disabled={isLoading || !billName.trim() || !amount || !category}
        >
          {isLoading ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <Text style={styles.saveText}>Add Bill</Text>
          )}
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 18,
    backgroundColor: "#f9f9fb",
    flexGrow: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f9f9fb',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f9f9fb',
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E293B',
    marginTop: 16,
    marginBottom: 8,
  },
  errorMessage: {
    fontSize: 16,
    color: '#64748B',
    textAlign: 'center',
  },
  label: {
    fontSize: 14,
    color: "#333",
    marginBottom: 6,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    fontSize: 16,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  dateText: {
    marginLeft: 8,
    color: "#333",
    fontSize: 16,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  toggleBtn: {
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  toggleOn: {
    backgroundColor: "#8AD0AB",
  },
  toggleOff: {
    backgroundColor: "#ddd",
  },
  toggleText: {
    color: "#fff",
    fontWeight: "600",
  },
  saveBtn: {
    backgroundColor: "#8AD0AB",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
    shadowColor: "#8AD0AB",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  saveBtnDisabled: {
    backgroundColor: "#cccccc",
    opacity: 0.6,
  },
  saveText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    overflow: "hidden",
  },
  periodicPicker: {
    marginTop: 10,
    marginBottom: 15,
  },
  selectionBarContainer: {
    flexDirection: "row",
    backgroundColor: "#8CCFB1",
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  typeButtonActive: {
    backgroundColor: "#fff",
  },
  typeButtonText: {
    color: "#2E5E4E",
    fontSize: 16,
    fontWeight: "500",
  },
  typeButtonTextActive: {
    color: "#2E5E4E",
    fontWeight: "bold",
  },
  periodicContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 15,
  },
});