import React, { useState, useRef } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  Switch,
  ActivityIndicator,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import DateTimePicker from "@react-native-community/datetimepicker";
import AppHeader from "../../reuseComponet/header";
import { addBillLocal,isBillNameDuplicate } from "../../../database/SQLite";
import { Picker } from '@react-native-picker/picker';
import { useUser } from "../../reuseComponet/UserContext";
import ValidatedInput from "../../reuseComponet/ValidatedInput";

export default function AddBill({ navigation }) {
  const [billName, setBillName] = useState("");
  const [category, setCategory] = useState("");
  const [amount, setAmount] = useState("");
  const [dueDate, setDueDate] = useState(new Date());
  const [showPicker, setShowPicker] = useState(false);
  const [isCommitment, setIsCommitment] = useState(false);

  const [isLoading, setIsLoading] = useState(false);
  const [isPeriodic, setIsPeriodic] = useState(false);
  const [selectedType, setSelectedType] = useState("Yearly");
  const [periodInterval, setPeriodInterval] = useState(0);

  const { userId, isLoading: userLoading } = useUser();

  const nameRef = useRef(null);
  const amountRef = useRef(null);

  const categories = [
    "Rent / Mortgage",
    "Utilities",
    "Internet / Phone",
    "Insurance",
    "Credit Card Payment",
    "Loan Repayment",
    "Subscription",
    "Groceries / Food",
    "Transportation / Fuel",
    "Education / Tuition",
    "Medical / Health Expenses",
    "Household / Maintenance",
    "Entertainment / Leisure",
    "Others",
  ];

  const handleSave = async () => {
    let valid = true;
    const isDuplicate = await isBillNameDuplicate(userId, billName);
    if (isDuplicate) {
      nameRef.current?.shake();
      nameRef.current?.setError(true);
      return Alert.alert("Duplicate Name", "A bill with this name already exists.");
    }

    if (!billName.trim()) {
      nameRef.current?.shake();
      nameRef.current?.setError(true);
      valid = false;
    }

    if (!amount.trim() || isNaN(amount) || Number(amount) <= 0) {
      amountRef.current?.shake();
      amountRef.current?.setError(true);
      valid = false;
    }

    if (!category) {
      Alert.alert("Missing Category", "Please select a category.");
      valid = false;
    }

    if (!valid) {
      return;
    }

    try {
      setIsLoading(true);

      await addBillLocal({
        userId,
        billName: billName.trim(),
        category,
        amount: parseFloat(amount),
        dueDate: dueDate.toISOString().split("T")[0],
        isAutoGenerated: isPeriodic ? 1 : 0,
        isCommitment: isCommitment ? 1 : 0,
        periodType: isPeriodic ? selectedType : "Yearly",
        periodInterval: isPeriodic ? Number(periodInterval) : 0,
      });

      Alert.alert("Success", "Bill added successfully!");
      navigation.goBack();

    } catch (error) {
      console.error("❌ addBillLocal error:", error);
      Alert.alert("Error", "Failed to add bill.");
    } finally {
      setIsLoading(false);
    }
  };

  if (userLoading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#8AD0AB" />
        <Text>Loading user data...</Text>
      </View>
    );
  }

  return (
    <View style={{ flex: 1 }}>
      <AppHeader title="Add New Bill" showLeftButton onLeftPress={() => navigation.goBack()} />

      <ScrollView contentContainerStyle={styles.container}>

        {/* BILL NAME */}
        <ValidatedInput
          ref={nameRef}
          label="Bill Name"
          value={billName}
          onChangeText={setBillName}
          placeholder="e.g. Credit Card"
          placeholderTextColor={"#c5c5c5ff"}
          validate={(v) => v.trim().length > 0}
          errorMessage="Bill name cannot be empty"
        />

        {/* CATEGORY */}
        <Text style={styles.label}>Category</Text>
        <View style={styles.pickerContainer}>
          <Picker
            selectedValue={category}
            onValueChange={(itemValue) => setCategory(itemValue)}
          >
            <Picker.Item label="Select category..." value="" />
            {categories.map((c) => (
              <Picker.Item key={c} label={c} value={c} />
            ))}
          </Picker>
        </View>

        {/* AMOUNT */}
        <ValidatedInput
          ref={amountRef}
          label="Amount (RM)"
          value={amount}
          onChangeText={setAmount}
          placeholder="Enter amount"
          placeholderTextColor={"#c5c5c5ff"}
          keyboardType="numeric"
          validate={(v) => !isNaN(v) && Number(v) > 0}
          errorMessage="Please enter a valid amount"
        />

        {/* DUE DATE */}
        <Text style={styles.label}>Due Date</Text>
        <TouchableOpacity style={styles.dateInput} onPress={() => setShowPicker(true)}>
          <Ionicons name="calendar-outline" size={18} color="#6c757d" />
          <Text style={styles.dateText}>
            {dueDate.toLocaleDateString("en-GB", {
              day: "numeric",
              month: "short",
              year: "numeric",
            })}
          </Text>
        </TouchableOpacity>

        {showPicker && (
          <DateTimePicker
            value={dueDate}
            mode="date"
            display="default"
            onChange={(event, date) => {
              setShowPicker(false);
              if (date) setDueDate(date);
            }}
          />
        )}

        {/* PERIODIC SWITCH */}
        <View style={styles.periodicContainer}>
          <Text style={styles.label}>Is it periodic?</Text>
          <Switch
            value={isPeriodic}
            onValueChange={setIsPeriodic}
            trackColor={{ false: "#ccc", true: "#9cd8b3" }}
            thumbColor={isPeriodic ? "#4CAF50" : "#f4f3f4"}
          />
        </View>

        {isPeriodic && (
          <>
            <View style={styles.selectionBarContainer}>
              {["Yearly", "Monthly"].map((type) => (
                <TouchableOpacity
                  key={type}
                  style={[styles.typeButton, selectedType === type && styles.typeButtonActive]}
                  onPress={() => setSelectedType(type)}
                >
                  <Text style={[styles.typeButtonText, selectedType === type && styles.typeButtonTextActive]}>
                    {type}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>

            <Text style={styles.label}>Repeat every:</Text>
            <View style={styles.pickerContainer}>
              <Picker selectedValue={periodInterval} onValueChange={(val) => setPeriodInterval(val)}>
                {[1, 2, 3, 6, 12].map((n) => (
                  <Picker.Item key={n} label={`${n}`} value={n} />
                ))}
              </Picker>
            </View>
          </>
        )}

        {/* Save Button */}
        <TouchableOpacity style={styles.saveBtn} onPress={handleSave}>
          {isLoading ? <ActivityIndicator size="small" color="#fff" /> : <Text style={styles.saveText}>Add Bill</Text>}
        </TouchableOpacity>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { padding: 18, backgroundColor: "#f9f9fb", flexGrow: 1 },
  label: { fontSize: 14, fontWeight: "600", marginBottom: 6 },
  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 12,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  dateText: { marginLeft: 8 },
  periodicContainer: { flexDirection: "row", justifyContent: "space-between", marginBottom: 15, marginTop: 15 },
  selectionBarContainer: {
    flexDirection: "row",
    backgroundColor: "#8CCFB1",
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
  },
  typeButton: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: "center" },
  typeButtonActive: { backgroundColor: "#fff" },
  typeButtonText: { color: "#2E5E4E" },
  typeButtonTextActive: { fontWeight: "bold" },
  saveBtn: {
    backgroundColor: "#8AD0AB",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  saveText: { color: "#fff", fontSize: 16, fontWeight: "700" },
});
