import React, { useState, useRef } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  Switch,
  ActivityIndicator,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import DateTimePicker from "@react-native-community/datetimepicker";
import AppHeader from "../../reuseComponet/header";
import { addBillLocal, isBillNameDuplicate } from "../../../database/SQLite";
import { Picker } from '@react-native-picker/picker';
import { useUser } from "../../reuseComponet/UserContext";
import {
  FDSCard,
  FDSValidatedInput,
  FDSValidatedPicker,
  FDSLabel,
  FDSButton,
  FDSColors
} from "../../reuseComponet/DesignSystem";

export default function AddBill({ navigation }) {
  const [billName, setBillName] = useState("");
  const [category, setCategory] = useState("");
  const [amount, setAmount] = useState("");
  const [dueDate, setDueDate] = useState(new Date());
  const [showPicker, setShowPicker] = useState(false);
  const [isCommitment, setIsCommitment] = useState(false);

  const [isLoading, setIsLoading] = useState(false);
  const [isPeriodic, setIsPeriodic] = useState(false);
  const [selectedType, setSelectedType] = useState("Yearly");
  const [periodInterval, setPeriodInterval] = useState(0);

  const { userId, isLoading: userLoading } = useUser();

  const nameRef = useRef(null);
  const amountRef = useRef(null);
  const categoryRef = useRef(null);

  const categories = [
    "Rent / Mortgage",
    "Utilities",
    "Internet / Phone",
    "Insurance",
    "Credit Card Payment",
    "Loan Repayment",
    "Subscription",
    "Groceries / Food",
    "Transportation / Fuel",
    "Education / Tuition",
    "Medical / Health Expenses",
    "Household / Maintenance",
    "Entertainment / Leisure",
    "Others",
  ];

  const handleSave = async () => {
    let valid = true;
    const isDuplicate = await isBillNameDuplicate(userId, billName);
    if (isDuplicate) {
      nameRef.current?.shake();
      nameRef.current?.setError(true);
      return Alert.alert("Duplicate Name", "A bill with this name already exists.");
    }

    if (!billName.trim()) {
      nameRef.current?.shake();
      nameRef.current?.setError(true);
      valid = false;
    }

    if (!amount.trim() || isNaN(amount) || Number(amount) <= 0) {
      amountRef.current?.shake();
      amountRef.current?.setError(true);
      valid = false;
    }

    if (!category) {
      categoryRef.current?.setError(true);
      categoryRef.current?.shake();
      valid = false;
    }

    if (!valid) {
      return;
    }

    try {
      setIsLoading(true);

      await addBillLocal({
        userId,
        billName: billName.trim(),
        category,
        amount: parseFloat(amount),
        dueDate: dueDate.toISOString().split("T")[0],
        isAutoGenerated: isPeriodic ? 1 : 0,
        isCommitment: isCommitment ? 1 : 0,
        periodType: isPeriodic ? selectedType : "Yearly",
        periodInterval: isPeriodic ? Number(periodInterval) : 0,
      });

      Alert.alert("Success", "Bill added successfully!");
      navigation.goBack();

    } catch (error) {
      console.error("❌ addBillLocal error:", error);
      Alert.alert("Error", "Failed to add bill.");
    } finally {
      setIsLoading(false);
    }
  };

  if (userLoading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#8AD0AB" />
        <Text>Loading user data...</Text>
      </View>
    );
  }

  return (
    <View style={{ flex: 1 }}>
      <AppHeader title="Add New Bill" showLeftButton onLeftPress={() => navigation.goBack()} />

      <ScrollView contentContainerStyle={styles.container}>
        <FDSCard>

          {/* BILL NAME */}
          <FDSValidatedInput
            ref={nameRef}
            label="Bill Name"
            value={billName}
            onChangeText={setBillName}
            placeholder="e.g. Credit Card"
            validate={(v) => v && v.trim().length > 0}
            errorMessage="Bill name cannot be empty"
            icon={<Ionicons name="document-text-outline" size={18} color={FDSColors.textGray} />}
          />

          {/* AMOUNT */}
          <FDSValidatedInput
            ref={amountRef}
            label="Amount (RM)"
            value={amount}
            onChangeText={setAmount}
            keyboardType="numeric"
            validate={(v) => !isNaN(v) && Number(v) > 0}
            errorMessage="Please enter a valid amount"
            icon={<Ionicons name="cash-outline" size={18} color={FDSColors.textGray} />}
          />


          {/* CATEGORY */}
          <FDSValidatedPicker
            ref={categoryRef}
            label="Category"
            value={category}
            validate={(v) => v && v !== ""}
            errorMessage="Category is required"
            icon={<Ionicons name="list-circle-outline" size={18} color={FDSColors.textGray} />}
          >
            <Picker
              selectedValue={category}
              onValueChange={setCategory}
              style={{ position: "absolute", opacity: 0, width: "100%" }}
            >
              <Picker.Item label="Select category..." value="" />
              {categories.map((c) => (
                <Picker.Item key={c} label={c} value={c} />
              ))}
            </Picker>
          </FDSValidatedPicker>

          {/* DUE DATE */}
          <FDSLabel>Due Date</FDSLabel>
          <TouchableOpacity style={[styles.dateInput, { backgroundColor: FDSColors.bgLight, borderColor: FDSColors.border }]} onPress={() => setShowPicker(true)}>
            <Ionicons name="calendar-outline" size={18} color="#6c757d" />
            <Text style={styles.dateText}>
              {dueDate.toLocaleDateString("en-GB", {
                day: "numeric",
                month: "short",
                year: "numeric",
              })}
            </Text>
          </TouchableOpacity>

          {showPicker && (
            <DateTimePicker
              value={dueDate}
              mode="date"
              display="default"
              onChange={(event, date) => {
                setShowPicker(false);
                if (date) setDueDate(date);
              }}
            />
          )}

          {/* Loan Commitment */}
          <View style={styles.toggleRow}>
            <View style={{ flexDirection: "row", alignItems: "center" }}>
              <Text style={styles.label}>Count as Loan Commitment?</Text>
              <TouchableOpacity
                style={{ marginLeft: 6 }}
                onPress={() =>
                  Alert.alert(
                    "What is Loan Commitment?",
                    "Select YES if this bill is a loan or financing repayment."
                  )
                }
              >
                <Ionicons name="information-circle-outline" size={18} color="#6c757d" />
              </TouchableOpacity>
            </View>

            <TouchableOpacity
              style={[styles.toggleBtn, isCommitment ? styles.toggleOn : styles.toggleOff]}
              onPress={() => setIsCommitment(!isCommitment)}
            >
              <Text style={styles.toggleText}>{isCommitment ? "Yes" : "No"}</Text>
            </TouchableOpacity>
          </View>


          {/* PERIODIC SWITCH */}
          <View style={styles.periodicContainer}>
            <FDSLabel>Is it periodic?</FDSLabel>
            <Switch
              value={isPeriodic}
              onValueChange={setIsPeriodic}
              trackColor={{ false: "#ccc", true: "#9cd8b3" }}
              thumbColor={isPeriodic ? "#4CAF50" : "#f4f3f4"}
            />
          </View>

          {isPeriodic && (
            <>
              <View style={styles.selectionBarContainer}>
                {["Yearly", "Monthly"].map((type) => (
                  <TouchableOpacity
                    key={type}
                    style={[styles.typeButton, selectedType === type && styles.typeButtonActive]}
                    onPress={() => setSelectedType(type)}
                  >
                    <Text style={[styles.typeButtonText, selectedType === type && styles.typeButtonTextActive]}>
                      {type}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>

              <FDSValidatedPicker
                label="Repeat every"
                value={periodInterval}
                validate={(v) => v !== null && v !== undefined}
                errorMessage="Please select an interval"
                icon={<Ionicons name="repeat-outline" size={16} color={FDSColors.textGray} />}
              >
                <Picker
                  selectedValue={periodInterval}
                  onValueChange={(val) => setPeriodInterval(val)}
                  style={{ position: "absolute", opacity: 0, width: "100%" }}
                >
                  {[1, 2, 3, 6, 12].map((n) => (
                    <Picker.Item key={n} label={`${n}`} value={n} />
                  ))}
                </Picker>
              </FDSValidatedPicker>
            </>
          )}

        </FDSCard>

        {/* Save Button */}
        <FDSButton
          title={isLoading ? "Saving..." : "Add Bill"}
          onPress={handleSave}
          icon="save-outline"
        />

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { padding: 18, backgroundColor: "#f9f9fb", flexGrow: 1 },
  label: { fontSize: 14, fontWeight: "600", marginBottom: 6 },
  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 12,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  dateText: { marginLeft: 8 },
  periodicContainer: { flexDirection: "row", justifyContent: "space-between", marginBottom: 15, marginTop: 15 },
  selectionBarContainer: {
    flexDirection: "row",
    backgroundColor: "#8CCFB1",
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
  },
  typeButton: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: "center" },
  typeButtonActive: { backgroundColor: "#fff" },
  typeButtonText: { color: "#2E5E4E" },
  typeButtonTextActive: { fontWeight: "bold" },
  saveBtn: {
    backgroundColor: "#8AD0AB",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  saveText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  toggleBtn: {
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  toggleOn: { backgroundColor: "#8AD0AB" },
  toggleOff: { backgroundColor: "#ddd" },
  toggleText: { color: "#fff", fontWeight: "600" },
});
