import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  Alert,
  Switch,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import DateTimePicker from "@react-native-community/datetimepicker";
import AppHeader from "../../reuseComponet/header";
import { updateBillLocal, deleteBillLocal } from "../../../database/SQLite";
import { Picker } from "@react-native-picker/picker";
import { useRef } from "react";
import {
  FDSCard,
  FDSValidatedInput,
  FDSValidatedPicker,
  FDSLabel,
  FDSButton,
  FDSColors
} from "../../reuseComponet/DesignSystem";



export default function BillDetail({ route, navigation }) {
  const { bill } = route.params;

  const [billName, setBillName] = useState("");
  const [category, setCategory] = useState("");
  const [amount, setAmount] = useState("");
  const [dueDate, setDueDate] = useState(new Date());
  const [showPicker, setShowPicker] = useState(false);

  const [isCommitment, setIsCommitment] = useState(false);

  const [isPeriodic, setIsPeriodic] = useState(false);
  const [selectedType, setSelectedType] = useState("Yearly");
  const [periodInterval, setPeriodInterval] = useState(1);

  const periodTypeOptions = ["Yearly", "Monthly"];
  const [periodTypeError, setPeriodTypeError] = useState(false);


  const categories = [
    "Rent / Mortgage",
    "Utilities",
    "Internet / Phone",
    "Insurance",
    "Credit Card Payment",
    "Loan Repayment",
    "Subscription",
    "Groceries / Food",
    "Transportation / Fuel",
    "Education / Tuition",
    "Medical / Health Expenses",
    "Household / Maintenance",
    "Entertainment / Leisure",
    "Others",
  ];
  const billNameRef = useRef(null);
  const amountRef = useRef(null);
  const categoryRef = useRef(null);
  const intervalRef = useRef(null);
  const periodTypeRef = useRef(null);


  // Prefill existing bill
  useEffect(() => {
    if (bill) {
      setBillName(bill.billName);
      setCategory(bill.category);
      setAmount(String(bill.amount));
      setDueDate(new Date(bill.dueDate + "T00:00:00"));

      setIsCommitment(bill.isCommitment === 1);
      setIsPeriodic(bill.isAutoGenerated === 1);

      setSelectedType(periodTypeOptions.includes(bill.periodType) ? bill.periodType : "Yearly");
      setPeriodInterval(bill.periodInterval > 0 ? bill.periodInterval : 1);
    }
  }, [bill]);




  // ---------------- UPDATE ----------------

  const handleSave = async () => {
    const validName = billNameRef.current?.validate();
    const validCat = categoryRef.current?.validate();
    const validAmount = amountRef.current?.validate();

    let validInterval = true;
    if (isPeriodic) {
      validInterval = intervalRef.current?.validate();
    }

    if (!validName || !validCat || !validAmount || !validInterval) return;
    let validPeriodType = true;
    if (isPeriodic) {
      if (!periodTypeOptions.includes(selectedType)) {
        validPeriodType = false;
        setPeriodTypeError(true);
        periodTypeRef.current?.shake?.(); // If you add shake ref
      }
    }
    if (!validPeriodType) return;



    const newData = {
      billName: billName.trim(),
      category,
      amount: parseFloat(amount),
      dueDate: dueDate.toISOString().split("T")[0],
      isCommitment: isCommitment ? 1 : 0,
      isAutoGenerated: isPeriodic ? 1 : 0,
      periodType: isPeriodic ? selectedType : "Yearly",
      periodInterval: isPeriodic ? Number(periodInterval) : 0,
    };

    const oldData = {
      billName: bill.billName,
      category: bill.category,
      amount: bill.amount,
      dueDate: bill.dueDate,
      isCommitment: bill.isCommitment,
      isAutoGenerated: bill.isAutoGenerated,
      periodType: bill.periodType,
      periodInterval: bill.periodInterval,
    };

    // ⚠️ Compare — skip update if nothing changed
    const unchanged = JSON.stringify(newData) === JSON.stringify(oldData);

    if (unchanged) {
      Alert.alert("No Changes", "You didn’t modify any fields.");
      return;
    }

    try {
      await updateBillLocal(bill.userId, bill.id, newData);

      Alert.alert("Success", "Bill updated successfully!");
      navigation.goBack();
    } catch (err) {
      console.error("❌ updateBillLocal error:", err);
      Alert.alert("Error", "Failed to update bill.");
    }
  };


  // ---------------- DELETE ----------------
  const handleDelete = async () => {

    if (!bill?.userId) {
      Alert.alert("Error", "Cannot delete bill: User ID missing");
      return;
    }

    if (!bill?.id) {
      Alert.alert("Error", "Cannot delete bill: Bill ID missing");
      return;
    }

    Alert.alert(
      "Delete Bill",
      "Are you sure you want to delete this bill and all its reminders? This action cannot be undone.",
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: async () => {
            try {

              const result = await deleteBillLocal(bill.userId, bill.id);

              if (result) {
                Alert.alert("Success", "Bill and all reminders deleted successfully!", [
                  {
                    text: "OK",
                    onPress: () => {
                      navigation.goBack();
                    }
                  }
                ]);
              } else {
                Alert.alert("Error", "Failed to delete bill");
              }
            } catch (error) {
              Alert.alert("Error", "Failed to delete bill: " + error.message);
            }
          }
        }
      ]
    );
  };
  return (
    <View style={{ flex: 1 }}>
      <AppHeader
        title="Edit Bill"
        showLeftButton
        onLeftPress={() => navigation.goBack()}
      />

      <ScrollView contentContainerStyle={styles.container}>
        <FDSCard>
          {/* Bill Name */}
          <FDSValidatedInput
            ref={billNameRef}
            label="Bill Name"
            value={billName}
            onChangeText={setBillName}
            placeholder="Enter bill name"
            validate={(v) => v && v.trim().length > 0}
            errorMessage="Bill name cannot be empty"
            icon={<Ionicons name="document-text-outline" size={18} color={FDSColors.textGray} />}
          />

          {/* Category */}
          <FDSValidatedPicker
            ref={categoryRef}
            label="Category"
            value={category}
            validate={(v) => !!v}
            errorMessage="Category is required"
            icon={<Ionicons name="list-circle-outline" size={18} color={FDSColors.textGray} />}
          >
            <Picker
              selectedValue={category}
              onValueChange={(v) => {
                if (v === "__add_new_category__") {
                  navigation.navigate("AddCategory", {
                    onCategoryAdded: (newCat) => {
                      setCategory(newCat);
                      categoryRef.current?.clearError();
                    }
                  });
                } else {
                  setCategory(v);
                }
              }}
              style={{ opacity: 0, width: "100%", position: "absolute" }}
            >
              <Picker.Item label="Select category..." value="" />
              {categories.map((c) => (
                <Picker.Item key={c} label={c} value={c} />
              ))}
              <Picker.Item label="➕ Add new category" value="__add_new_category__" />
            </Picker>
          </FDSValidatedPicker>

          {/* Amount */}
          <FDSValidatedInput
            ref={amountRef}
            label="Amount (RM)"
            value={amount}
            onChangeText={setAmount}
            keyboardType="numeric"
            validate={(v) => v && !isNaN(v) && Number(v) > 0}
            errorMessage="Please enter a valid amount"
            icon={<Ionicons name="cash-outline" size={18} color={FDSColors.textGray} />}
          />

          {/* Due Date */}
          <FDSLabel>Due Date</FDSLabel>
          <TouchableOpacity style={styles.dateInput} onPress={() => setShowPicker(true)}>
            <Ionicons name="calendar-outline" size={18} color="#6c757d" />
            <Text style={styles.dateText}>{dueDate.toDateString()}</Text>
          </TouchableOpacity>

          {showPicker && (
            <DateTimePicker
              value={dueDate}
              mode="date"
              display="default"
              onChange={(event, date) => {
                setShowPicker(false);
                if (date) setDueDate(date);
              }}
            />
          )}

          {/* Periodic Switch */}
          <View style={styles.periodicContainer}>
            <Text style={styles.label}>Is it periodic?</Text>
            <Switch
              value={isPeriodic}
              onValueChange={setIsPeriodic}
              trackColor={{ false: "#ccc", true: "#9cd8b3" }}
              thumbColor={isPeriodic ? "#4CAF50" : "#f4f3f4"}
            />
          </View>

          {/* Period Type + Interval (only if periodic) */}
          {isPeriodic && (
            <>
              <View
                ref={periodTypeRef}
                style={[
                  styles.selectionBarContainer,
                  periodTypeError && { borderColor: "#FF6B6B", borderWidth: 2 },
                ]}
              >
                {periodTypeOptions.map((type) => (
                  <TouchableOpacity
                    key={type}
                    style={[
                      styles.typeButton,
                      selectedType === type && styles.typeButtonActive,
                    ]}
                    onPress={() => {
                      setSelectedType(type);
                      setPeriodTypeError(false);
                    }}
                  >
                    <Text
                      style={[
                        styles.typeButtonText,
                        selectedType === type && styles.typeButtonTextActive,
                      ]}
                    >
                      {type}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
              {periodTypeError && (
                <Text style={{ color: "#FF6B6B", marginBottom: 8 }}>
                  Please select a valid repeat type
                </Text>
              )}


              <FDSValidatedPicker
                ref={intervalRef}
                label="Repeat every"
                value={periodInterval}
                validate={(v) => v && Number(v) > 0}
                errorMessage="Interval required"
                icon={<Ionicons name="repeat-outline" size={18} color={FDSColors.textGray} />}
              >
                <Picker
                  selectedValue={periodInterval}
                  onValueChange={(v) => setPeriodInterval(v)}
                  style={{ opacity: 0, width: "100%", position: "absolute" }}
                >
                  {[1, 2, 3, 6, 12].map((n) => (
                    <Picker.Item key={n} label={`${n}`} value={n} />
                  ))}
                </Picker>
              </FDSValidatedPicker>
            </>
          )}

          {/* Loan Commitment */}
          <View style={styles.toggleRow}>
            <View style={{ flexDirection: "row", alignItems: "center" }}>
              <Text style={styles.label}>Count as Loan Commitment?</Text>
              <TouchableOpacity
                style={{ marginLeft: 6 }}
                onPress={() =>
                  Alert.alert(
                    "What is Loan Commitment?",
                    "Select YES if this bill is a loan or financing repayment."
                  )
                }
              >
                <Ionicons name="information-circle-outline" size={18} color="#6c757d" />
              </TouchableOpacity>
            </View>

            <TouchableOpacity
              style={[styles.toggleBtn, isCommitment ? styles.toggleOn : styles.toggleOff]}
              onPress={() => setIsCommitment(!isCommitment)}
            >
              <Text style={styles.toggleText}>{isCommitment ? "Yes" : "No"}</Text>
            </TouchableOpacity>
          </View>

          {/* Save */}
          <FDSButton
            title="Save Changes"
            icon="save-outline"
            onPress={handleSave}
          />

          {/* Delete */}
          <FDSButton
            title="Delete Bill"
            icon="trash-outline"
            onPress={handleDelete}
            bgColor="#E53935"
            textColor="#FFFFFF"
          />
        </FDSCard>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { padding: 18, backgroundColor: "#f9f9fb" },
  label: { fontSize: 14, color: "#333", marginBottom: 6, fontWeight: "600" },
  input: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  pickerContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 12,
    height: 48,
    justifyContent: "center",
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  dateText: {
    marginLeft: 8,
    color: "#333",
  },
  periodicContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 15,
  },
  selectionBarContainer: {
    flexDirection: "row",
    backgroundColor: "#8CCFB1",
    borderRadius: 8,
    padding: 4,
    marginBottom: 20,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  typeButtonActive: {
    backgroundColor: "#fff",
  },
  typeButtonText: {
    color: "#2E5E4E",
    fontSize: 16,
    fontWeight: "500",
  },
  typeButtonTextActive: {
    color: "#2E5E4E",
    fontWeight: "bold",
  },
  picker: { backgroundColor: "#fff", borderRadius: 8, marginBottom: 12 },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  toggleBtn: {
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  toggleOn: { backgroundColor: "#8AD0AB" },
  toggleOff: { backgroundColor: "#ddd" },
  toggleText: { color: "#fff", fontWeight: "600" },
  saveBtn: {
    backgroundColor: "#8AD0AB",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  saveText: { color: "#fff", fontWeight: "700" },
  deleteBtn: {
    backgroundColor: "#FF6B6B",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  deleteText: { color: "#fff", fontWeight: "700" },
});
