import { Alert } from "react-native";
import { getAutoGeneratedBillsLocal, addBillLocal } from "../../../database/SQLite";
import { useUser } from "../../reuseComponet/UserContext";

export const processPeriodicBills = async (userId) => {
  const bills = await getAutoGeneratedBillsLocal(userId);
  const today = new Date();

  console.log("Trigger processPeriodicBills");

  for (const bill of bills) {
    // skip non-periodic bills
    if (!bill.periodType || bill.periodInterval <= 0) continue;

    let lastDue = new Date(bill.dueDate);
    let nextDue = new Date(lastDue);

    if (bill.periodType === "Monthly") {
      nextDue.setMonth(lastDue.getMonth() + bill.periodInterval);
    } else if (bill.periodType === "Yearly") {
      nextDue.setFullYear(lastDue.getFullYear() + bill.periodInterval);
    }

    // check if we need to generate
    if (nextDue <= today) {
      const existing = bills.find(
        b => b.userId === bill.userId &&
          b.billName === bill.billName &&
          b.dueDate === nextDue.toISOString().split("T")[0]
      );

      if (!existing) {
        await addBillLocal({
          userId: bill.userId,
          billName: bill.billName,
          category: bill.category,
          amount: bill.amount,
          dueDate: nextDue.toISOString().split("T")[0],
          status: "Upcoming",
          isAutoGenerated: 1,
          isCommitment: bill.isCommitment,
          periodType: bill.periodType,
          periodInterval: bill.periodInterval,
        });

        Alert.alert(
          "New Bill Generated",
          `Auto-generated periodic bill: ${bill.billName}, Due: ${nextDue.toISOString().split("T")[0]}`
        );
        console.log(`✅ Auto-created new periodic bill for ${bill.billName}`);
      }
    }
  }
};
